"""One-shot script: extract hardcoded trainingPresets from useTrainingForm.ts into JSON files."""
import json, os, re

PRESETS_DIR = os.path.join(os.path.dirname(__file__), '..', 'presets')
os.makedirs(PRESETS_DIR, exist_ok=True)

# All 42 hardcoded presets, transcribed verbatim from useTrainingForm.ts
presets = {
  "sdxl_character": {
    "name": "SDXL Character",
    "description": "Optimized for training character LoRAs on SDXL",
    "model_type": "SDXL",
    "resolution": 1024, "network_dim": 32, "network_alpha": 32,
    "unet_lr": 0.0001, "text_encoder_lr": 0.00005,
    "lr_scheduler": "cosine_with_restarts", "lr_scheduler_number": 3,
    "optimizer_type": "AdamW8bit", "max_train_epochs": 10,
    "train_batch_size": 1, "clip_skip": 2,
  },
  "sdxl_style": {
    "name": "SDXL Style",
    "description": "For training art style LoRAs on SDXL",
    "model_type": "SDXL",
    "resolution": 1024, "network_dim": 64, "network_alpha": 64,
    "unet_lr": 0.0002, "text_encoder_lr": 0.0001,
    "lr_scheduler": "cosine", "optimizer_type": "Prodigy",
    "max_train_epochs": 15, "train_batch_size": 2, "clip_skip": 2,
  },
  "sd15_character": {
    "name": "SD1.5 Character",
    "description": "Classic SD1.5 character training",
    "model_type": "SD15",
    "resolution": 512, "network_dim": 32, "network_alpha": 32,
    "unet_lr": 0.0001, "text_encoder_lr": 0.00005,
    "lr_scheduler": "cosine_with_restarts", "lr_scheduler_number": 3,
    "optimizer_type": "AdamW8bit", "max_train_epochs": 10,
    "train_batch_size": 4, "clip_skip": 1,
  },
  "flux_experimental": {
    "name": "Flux (Experimental)",
    "description": "Experimental Flux.1 training",
    "model_type": "FLUX",
    "resolution": 1024, "network_dim": 16, "network_alpha": 16,
    "unet_lr": 0.0001, "text_encoder_lr": 0,
    "lr_scheduler": "constant", "optimizer_type": "AdamW8bit",
    "max_train_epochs": 5, "train_batch_size": 1,
    "guidance_scale": 3.5, "timestep_sampling": "flux_shift",
  },
  "mj52_style_juggernaut": {
    "name": "MJ5.2 Style (JuggernautXL)",
    "description": "Midjourney 5.2 style emulation on JuggernautXL. Extreme dim 320/alpha 1 (1:320 ratio — maximum capacity, minimum scaling), Adafactor fixed-LR, 214 images × 20 repeats, 5 full epochs.",
    "model_type": "SDXL",
    "resolution": 1024, "network_dim": 320, "network_alpha": 1,
    "unet_lr": 0.0004, "text_encoder_lr": 0.0004,
    "lr_scheduler": "constant", "optimizer_type": "AdaFactor",
    "optimizer_args": "scale_parameter=False relative_step=False warmup_init=False",
    "max_train_epochs": 5, "save_every_n_epochs": 1,
    "train_batch_size": 2, "mixed_precision": "bf16",
  },
  "kappaneuro_illustrious_highdim": {
    "name": "KappaNeuro's High Dim Illustrious",
    "description": "Illustrious style LoRA with massive dim 256/alpha 32 (8:1 ratio). Plain AdamW (not 8bit!), constant scheduler, all LRs equal 1e-4, SNR=5. Expensive — 15h+ run. Pick checkpoint around epoch 12/17.",
    "model_type": "SDXL",
    "resolution": 1024, "network_dim": 256, "network_alpha": 32,
    "unet_lr": 0.0001, "text_encoder_lr": 0.0001,
    "lr_scheduler": "constant", "optimizer_type": "AdamW",
    "max_train_epochs": 17, "save_every_n_epochs": 1,
    "train_batch_size": 2, "mixed_precision": "bf16",
    "noise_offset": 0.0375, "min_snr_gamma": 5, "min_snr_gamma_enabled": True,
  },
  "kappaneuro_mucha_style": {
    "name": "KappaNeuro's Mucha Style (SDXL)",
    "description": "KappaNeuro Alphonse Mucha style LoRA. Extremely fast — 3 epochs, 16 min, batch 8. dim 32/alpha 8 (4:1 conservative), frozen TE, cosine, low noise_offset=0.03.",
    "model_type": "SDXL",
    "resolution": 1024, "network_dim": 32, "network_alpha": 8,
    "unet_lr": 0.0004, "text_encoder_lr": 0,
    "lr_scheduler": "cosine", "optimizer_type": "AdamW8bit",
    "optimizer_args": "weight_decay=0.1 betas=(0.9,0.99)",
    "max_train_epochs": 3, "save_every_n_epochs": 1,
    "train_batch_size": 8, "mixed_precision": "bf16", "noise_offset": 0.03,
  },
  "add_details_xl": {
    "name": "Add Details XL (Utility LoRA)",
    "description": "Detail-enhancement utility LoRA approach. 29 images × 30 repeats, 1 epoch only, triple dropout (rank+module+network=0.1) to prevent memorization. Uses HuggingFace model ID directly.",
    "model_type": "SDXL",
    "resolution": 1024, "network_dim": 64, "network_alpha": 32,
    "unet_lr": 0.0001, "text_encoder_lr": 0.0001,
    "lr_scheduler": "cosine_with_restarts", "optimizer_type": "AdamW8bit",
    "max_train_epochs": 1, "save_every_n_epochs": 1,
    "train_batch_size": 1, "mixed_precision": "bf16",
    "noise_offset": 0.1, "min_snr_gamma": 5, "min_snr_gamma_enabled": True,
    "network_dropout": 0.1, "rank_dropout": 0.1, "module_dropout": 0.1,
  },
  "faetastic_sdxl_prodigy": {
    "name": "FaeTastic Style (SDXL Prodigy)",
    "description": "FaeTastic SDXL style LoRA. Prodigy with cosine (unusual — decay stacks on adaptation), weight_decay=0.5 + bias_correction=False, unified LR=1. noise_offset=0.0357. dim 64/64, 100 images × 5 repeats.",
    "model_type": "SDXL",
    "resolution": 1024, "network_dim": 64, "network_alpha": 64,
    "unet_lr": 1, "text_encoder_lr": 1,
    "lr_scheduler": "cosine", "optimizer_type": "Prodigy",
    "optimizer_args": "decouple=True weight_decay=0.5 betas=(0.9,0.99) use_bias_correction=False",
    "max_train_epochs": 20, "save_every_n_epochs": 2,
    "train_batch_size": 1, "mixed_precision": "bf16", "noise_offset": 0.0357,
  },
  "lah_cutedoodle_sd15": {
    "name": "Lah's Cutedoodle (SD1.5)",
    "description": "Lah's cute doodle style on SD1.5/AnythingV5. dim 64/32, 768px, constant scheduler, adaptive_noise_scale=0.00357 (1/10 of noise_offset). Stopped at epoch 8/10.",
    "model_type": "SD15",
    "resolution": 768, "network_dim": 64, "network_alpha": 32,
    "unet_lr": 0.0001, "text_encoder_lr": 0.00005,
    "lr_scheduler": "constant", "optimizer_type": "AdamW8bit",
    "max_train_epochs": 10, "save_every_n_epochs": 1,
    "train_batch_size": 4, "mixed_precision": "fp16",
    "noise_offset": 0.05, "adaptive_noise_scale": 0.00357,
  },
  "lah_cutedoodle_xl": {
    "name": "Lah's Cutedoodle (XL)",
    "description": "Lah's cute doodle style on SDXL. TE LR (5e-4) HIGHER than UNet (1e-4) — inverted convention. Plain AdamW (not 8bit), constant, noise_offset=0.0357, adaptive_noise_scale=0.00357. Stopped epoch 12/15.",
    "model_type": "SDXL",
    "resolution": 1024, "network_dim": 32, "network_alpha": 32,
    "unet_lr": 0.0001, "text_encoder_lr": 0.0005,
    "lr_scheduler": "constant", "optimizer_type": "AdamW",
    "max_train_epochs": 15, "save_every_n_epochs": 1,
    "train_batch_size": 8, "mixed_precision": "bf16",
    "noise_offset": 0.0357, "adaptive_noise_scale": 0.00357,
  },
  "folk_horror_style_adafactor": {
    "name": "Folk Horror Style (SDXL Adafactor)",
    "description": "SDXL style LoRA with Adafactor fixed-LR mode. dim 32/16, active TE at 5e-5, noise_offset=0.1, SNR=5, batch 4. Essentially the Adafactor equivalent of Style Baking.",
    "model_type": "SDXL",
    "resolution": 1024, "network_dim": 32, "network_alpha": 16,
    "unet_lr": 0.0005, "text_encoder_lr": 0.00005,
    "lr_scheduler": "cosine_with_restarts",
    "optimizer_type": "AdaFactor",
    "optimizer_args": "scale_parameter=False relative_step=False warmup_init=False",
    "max_train_epochs": 10, "save_every_n_epochs": 1,
    "train_batch_size": 4, "mixed_precision": "bf16",
    "noise_offset": 0.1, "min_snr_gamma": 5, "min_snr_gamma_enabled": True,
  },
  "flat_color_anime_xl": {
    "name": "Flat Color Anime Style (Base SDXL)",
    "description": "Base SDXL flat color anime style. Extreme dim 128/alpha 1 ratio (1:128 scaling), Adafactor fixed-LR mode, active TE at 5e-5, stopped at epoch 23/25. Long run (~8h).",
    "model_type": "SDXL",
    "resolution": 1024, "network_dim": 128, "network_alpha": 1,
    "unet_lr": 0.0001, "text_encoder_lr": 0.00005,
    "lr_scheduler": "cosine_with_restarts",
    "optimizer_type": "AdaFactor",
    "optimizer_args": "scale_parameter=False relative_step=False warmup_init=False",
    "max_train_epochs": 25, "save_every_n_epochs": 1,
    "train_batch_size": 5, "mixed_precision": "bf16",
  },
  "anything_sd15_historical_2023": {
    "name": "Anything v4.5 (SD1.5 — Historical 2023)",
    "description": "June 2023 Anything v4.5 LoRA. HISTORICAL — alpha 128 / dim 32 (4:1 inverse, very aggressive scaling). Only ran 1/20 epochs (2 min) — likely a test or crash. Kept as historical curiosity.",
    "model_type": "SD15",
    "resolution": 512, "network_dim": 32, "network_alpha": 128,
    "unet_lr": 0.0001, "text_encoder_lr": 0.00001,
    "lr_scheduler": "cosine_with_restarts", "optimizer_type": "AdamW8bit",
    "max_train_epochs": 20, "save_every_n_epochs": 1,
    "train_batch_size": 2, "mixed_precision": "fp16",
  },
  "pastel_style_sd21_historical": {
    "name": "Pastel Style (SD 2.1 — Historical)",
    "description": "Feb 2023 Platdiffusion/SD 2.1 pastel style LoRA. HISTORICAL — predates standardized metadata. dim 96/alpha 12 (1:8 ratio), UNet 2x TE LR, 512px. WARNING: SD 2.1 not in model type enum — needs v2=true and OpenCLIP ViT-H. Use SD1.5 slot as workaround.",
    "model_type": "SD15",
    "resolution": 512, "network_dim": 96, "network_alpha": 12,
    "unet_lr": 0.0004, "text_encoder_lr": 0.0002,
    "lr_scheduler": "cosine", "optimizer_type": "AdamW",
    "max_train_epochs": 6, "save_every_n_epochs": 1,
    "train_batch_size": 2, "mixed_precision": "fp16",
  },
  "tensorart_dora_illustrious": {
    "name": "TensorArt DoRA (Illustrious)",
    "description": "Illustrious DoRA via lycoris.kohya (algo=lora + dora_wd=True). Larger dim 64/32, frozen TE, constant_with_warmup, noise_offset=0.03. Note: original used a server-side lycoris preset.toml and factor=8 — omitted here.",
    "model_type": "SDXL",
    "lora_type": "DoRA", "network_module": "lycoris.kohya",
    "resolution": 1024, "network_dim": 64, "network_alpha": 32,
    "unet_lr": 0.0001, "text_encoder_lr": 0,
    "lr_scheduler": "constant_with_warmup", "optimizer_type": "AdamW8bit",
    "max_train_epochs": 10, "save_every_n_epochs": 1,
    "train_batch_size": 2, "mixed_precision": "bf16", "noise_offset": 0.03,
  },
  "came_character_noob_batch6": {
    "name": "CAME Character (NoobAI, batch 6)",
    "description": "CAME character LoRA for NoobAI epsilon. Higher batch (6), SNR=8, UNet LR (6e-5) lower than base LR (1e-4). Stopped at epoch 10 of 15 — pick best checkpoint.",
    "model_type": "SDXL",
    "resolution": 1024, "network_dim": 8, "network_alpha": 4,
    "unet_lr": 0.00006, "text_encoder_lr": 0.000001,
    "lr_scheduler": "cosine", "optimizer_type": "CAME",
    "optimizer_args": "weight_decay=0.04",
    "max_train_epochs": 15, "save_every_n_epochs": 1,
    "train_batch_size": 6, "mixed_precision": "bf16",
    "min_snr_gamma": 8, "min_snr_gamma_enabled": True,
  },
  "compass_creature_noob": {
    "name": "Compass Attn-MLP (NoobAI)",
    "description": "NoobAI LyCORIS locon restricted to attn+MLP layers only (conv_dim=0, preset=attn-mlp), high LR, low SNR=1.5, effective batch 32. NOTE: Original used Compass optimizer (library.stochastic_optim) — mapped to AdamW until sourced.",
    "model_type": "SDXL",
    "lora_type": "LoCon", "network_module": "lycoris.kohya",
    "resolution": 1024, "network_dim": 16, "network_alpha": 16,
    "conv_dim": 0, "conv_alpha": 0,
    "unet_lr": 0.0006, "text_encoder_lr": 0.0001,
    "lr_scheduler": "cosine", "optimizer_type": "AdamW",
    "optimizer_args": "weight_decay=0 betas=(0.9,0.999)",
    "max_train_epochs": 6, "save_every_n_epochs": 1,
    "train_batch_size": 16, "gradient_accumulation_steps": 2,
    "mixed_precision": "bf16", "min_snr_gamma": 1.5, "min_snr_gamma_enabled": True,
  },
  "came_character_pony": {
    "name": "CAME Character (Pony)",
    "description": "CAME-based character LoRA for Pony. Small dim 8/4, near-frozen TE (1e-6), cosine, SNR=5, batch 2.",
    "model_type": "SDXL",
    "resolution": 1024, "network_dim": 8, "network_alpha": 4,
    "unet_lr": 0.0001, "text_encoder_lr": 0.000001,
    "lr_scheduler": "cosine", "optimizer_type": "CAME",
    "optimizer_args": "weight_decay=0.04",
    "max_train_epochs": 10, "save_every_n_epochs": 1,
    "train_batch_size": 2, "mixed_precision": "bf16",
    "min_snr_gamma": 5, "min_snr_gamma_enabled": True,
  },
  "came_character_illustrious": {
    "name": "CAME Character (Illustrious)",
    "description": "CAME-based character LoRA for Illustrious. Same as Pony variant but batch 1, no SNR.",
    "model_type": "SDXL",
    "resolution": 1024, "network_dim": 8, "network_alpha": 4,
    "unet_lr": 0.0001, "text_encoder_lr": 0.000001,
    "lr_scheduler": "cosine", "optimizer_type": "CAME",
    "optimizer_args": "weight_decay=0.04",
    "max_train_epochs": 10, "save_every_n_epochs": 1,
    "train_batch_size": 1, "mixed_precision": "bf16",
  },
  "came_character_initium": {
    "name": "CAME Character (Initium/NoobAI finetune)",
    "description": "CAME character LoRA for Initium (NoobAI finetune). 10x lower LR (3e-5), more epochs, noise_offset=0.0357.",
    "model_type": "SDXL",
    "resolution": 1024, "network_dim": 8, "network_alpha": 4,
    "unet_lr": 0.00003, "text_encoder_lr": 0.000007,
    "lr_scheduler": "cosine", "optimizer_type": "CAME",
    "optimizer_args": "weight_decay=0.04",
    "max_train_epochs": 17, "save_every_n_epochs": 1,
    "train_batch_size": 1, "mixed_precision": "bf16", "noise_offset": 0.0357,
  },
  "enigmata_character_noobai_vpred": {
    "name": "Enigmata's Character (NoobAI v-pred)",
    "description": "Published character LoRA by Enigmata (Igawa Asagi). NoobAI v-prediction, slightly lower LRs than epsilon version (1.2e-4 vs 1.4e-4), same multi-subset outfit dataset.",
    "model_type": "SDXL",
    "resolution": 1024, "network_dim": 32, "network_alpha": 16,
    "unet_lr": 0.00012, "text_encoder_lr": 0.00006,
    "lr_scheduler": "cosine_with_restarts", "optimizer_type": "AdamW8bit",
    "optimizer_args": "weight_decay=0.1 betas=(0.9,0.99)",
    "max_train_epochs": 13, "save_every_n_epochs": 1,
    "train_batch_size": 4, "mixed_precision": "bf16",
    "v_parameterization": True, "zero_terminal_snr": True,
    "scale_v_pred_loss_like_noise_pred": True,
    "min_snr_gamma": 5, "min_snr_gamma_enabled": True,
  },
  "enigmata_character_noobai": {
    "name": "Enigmata's Character (NoobAI)",
    "description": "Published character LoRA by Enigmata (Igawa Asagi). NoobAI epsilon, multi-subset outfit dataset, LR 1.4e-4 with betas=(0.9,0.99), SNR=5.",
    "model_type": "SDXL",
    "resolution": 1024, "network_dim": 32, "network_alpha": 16,
    "unet_lr": 0.00014, "text_encoder_lr": 0.00007,
    "lr_scheduler": "cosine_with_restarts", "optimizer_type": "AdamW8bit",
    "optimizer_args": "weight_decay=0.1 betas=(0.9,0.99)",
    "max_train_epochs": 13, "save_every_n_epochs": 1,
    "train_batch_size": 4, "mixed_precision": "bf16",
    "min_snr_gamma": 5, "min_snr_gamma_enabled": True,
  },
  "enigmata_character_pony": {
    "name": "Enigmata's Character (Pony)",
    "description": "Published character LoRA by Enigmata (Igawa Asagi). Pony base, smaller dim (16/8), lower LR 8e-5, no SNR, multi-subset outfit dataset.",
    "model_type": "SDXL",
    "resolution": 1024, "network_dim": 16, "network_alpha": 8,
    "unet_lr": 0.00008, "text_encoder_lr": 0.00004,
    "lr_scheduler": "cosine_with_restarts", "optimizer_type": "AdamW8bit",
    "optimizer_args": "weight_decay=0.1 betas=(0.9,0.99)",
    "max_train_epochs": 11, "save_every_n_epochs": 1,
    "train_batch_size": 4, "mixed_precision": "bf16",
  },
  "enigmata_character_sd15": {
    "name": "Enigmata's Character (SD1.5)",
    "description": "Published character LoRA by Enigmata (Igawa Asagi). SD1.5 base at 720px, large dim 64/32, higher LR 2e-4, balanced multi-subset repeats by outfit rarity.",
    "model_type": "SD15",
    "resolution": 720, "network_dim": 64, "network_alpha": 32,
    "unet_lr": 0.0002, "text_encoder_lr": 0.0001,
    "lr_scheduler": "cosine_with_restarts", "optimizer_type": "AdamW8bit",
    "max_train_epochs": 11, "save_every_n_epochs": 1,
    "train_batch_size": 2, "mixed_precision": "fp16", "noise_offset": 0.05,
  },
  "ktiseos_nyx_illustrious_character": {
    "name": "Ktiseos Nyx's Character (Illustrious)",
    "description": "Published Illustrious character LoRA recipe by ktiseos_nyx. AdamW8Bit with weight_decay=0.1, small active TE (5e-5), batch 3, multinoise, SNR=5. Solid baseline for character training.",
    "model_type": "SDXL",
    "resolution": 1024, "network_dim": 32, "network_alpha": 16,
    "unet_lr": 0.0005, "text_encoder_lr": 0.00005,
    "lr_scheduler": "cosine_with_restarts", "optimizer_type": "AdamW8bit",
    "optimizer_args": "weight_decay=0.1",
    "max_train_epochs": 10, "save_every_n_epochs": 1,
    "train_batch_size": 3, "mixed_precision": "bf16",
    "noise_offset": 0.1, "multires_noise_iterations": 6, "multires_noise_discount": 0.3,
    "min_snr_gamma": 5, "min_snr_gamma_enabled": True,
  },
  "flux_hard_bake_style": {
    "name": "Experimental Hard Bake Style (Flux)",
    "description": "Flux.1 D style LoRA using lora_flux. Same dim:2/alpha:16 ratio as Chroma preset — frozen TE, AdamW8Bit. The parallel experiment to the Chroma version.",
    "model_type": "FLUX",
    "network_module": "networks.lora_flux",
    "resolution": 1024, "network_dim": 2, "network_alpha": 16,
    "unet_lr": 0.0005, "text_encoder_lr": 0,
    "lr_scheduler": "cosine_with_restarts", "optimizer_type": "AdamW8bit",
    "optimizer_args": "weight_decay=0.01 eps=1e-08 betas=(0.9,0.999)",
    "max_train_epochs": 10, "save_every_n_epochs": 1,
    "train_batch_size": 2, "mixed_precision": "bf16",
    "noise_offset": 0.1, "multires_noise_iterations": 6, "multires_noise_discount": 0.3,
    "min_snr_gamma": 5, "min_snr_gamma_enabled": True,
  },
  "bolero537_yukata_noob": {
    "name": "bolero537's Yukata LoCon (NoobAI)",
    "description": "Published yukata clothing concept LoRA by bolero537. NoobAI epsilon, LoCon with extreme low alpha (16/1), Lion8bit, tiny dataset with heavy repeats (31 x 10).",
    "model_type": "SDXL",
    "lora_type": "LoCon", "network_module": "lycoris.kohya",
    "resolution": 1024, "network_dim": 16, "network_alpha": 1,
    "conv_dim": 16, "conv_alpha": 1,
    "unet_lr": 0.0001, "text_encoder_lr": 0,
    "lr_scheduler": "cosine_with_restarts", "optimizer_type": "Lion8bit",
    "max_train_epochs": 13, "save_every_n_epochs": 1,
    "train_batch_size": 2, "mixed_precision": "bf16",
    "min_snr_gamma": 6, "min_snr_gamma_enabled": True,
  },
  "bolero537_yukata_pony": {
    "name": "bolero537's Yukata (Pony)",
    "description": "Published yukata concept LoRA by bolero537. Pony base, Adafactor in adaptive mode (relative_step=True, self-scaling LR), extreme low alpha (8/1), same 31x10 dataset.",
    "model_type": "SDXL",
    "resolution": 1024, "network_dim": 8, "network_alpha": 1,
    "unet_lr": 0, "text_encoder_lr": 0,
    "lr_scheduler": "constant", "optimizer_type": "AdaFactor",
    "optimizer_args": "relative_step=True warmup_init=False",
    "max_train_epochs": 20, "save_every_n_epochs": 1,
    "train_batch_size": 2, "mixed_precision": "bf16",
    "min_snr_gamma": 6, "min_snr_gamma_enabled": True,
  },
  "bolero537_yukata_xl": {
    "name": "bolero537's Yukata (Base XL)",
    "description": "Published yukata concept LoRA by bolero537. Custom SDXL mix base, AdamW8Bit cosine, unified LR 2e-5, standard 32/16 dim/alpha, same 31x10 dataset.",
    "model_type": "SDXL",
    "resolution": 1024, "network_dim": 32, "network_alpha": 16,
    "unet_lr": 0.00002, "text_encoder_lr": 0,
    "lr_scheduler": "cosine", "optimizer_type": "AdamW8bit",
    "max_train_epochs": 10, "save_every_n_epochs": 1,
    "train_batch_size": 2, "mixed_precision": "bf16",
  },
  "motimalu_painterly_illustrious": {
    "name": "motimalu's Painterly Styles (Illustrious)",
    "description": "Published Illustrious painterly style LoRA by motimalu. Prodigy with aggressive weight_decay=0.5 and bias_correction=False, large 1278-image dataset, 50 full epochs.",
    "model_type": "SDXL",
    "resolution": 1024, "network_dim": 32, "network_alpha": 32,
    "unet_lr": 1, "text_encoder_lr": 1,
    "lr_scheduler": "constant", "optimizer_type": "Prodigy",
    "optimizer_args": "decouple=True weight_decay=0.5 betas=(0.9,0.99) use_bias_correction=False",
    "max_train_epochs": 50, "save_every_n_epochs": 5,
    "train_batch_size": 6, "mixed_precision": "bf16",
    "multires_noise_iterations": 6, "multires_noise_discount": 0.3,
    "min_snr_gamma": 5, "min_snr_gamma_enabled": True,
  },
  "silvermoong_noobai_loha": {
    "name": "silvermoong's LoHa (NoobAI v-pred)",
    "description": "Published Yoneyama Mai style LoRA by silvermoong. NoobAI v-prediction base, LoHa via LyCORIS, Prodigy at LR=1, massive effective batch (24x12=288). Pick checkpoint around epoch 115.",
    "model_type": "SDXL",
    "lora_type": "LoHa", "network_module": "lycoris.kohya",
    "resolution": 1024, "network_dim": 8, "network_alpha": 8,
    "unet_lr": 1, "text_encoder_lr": 1,
    "lr_scheduler": "constant", "optimizer_type": "Prodigy",
    "optimizer_args": "decouple=True weight_decay=0.01 use_bias_correction=True d_coef=2.0",
    "max_train_epochs": 200, "save_every_n_epochs": 5,
    "train_batch_size": 24, "gradient_accumulation_steps": 12,
    "mixed_precision": "bf16", "v_parameterization": True,
    "zero_terminal_snr": True, "scale_v_pred_loss_like_noise_pred": True,
  },
  "rgb_glitch_locon_dora": {
    "name": "xRikishi's DoRA + ADOPTAO",
    "description": "xRikishi's LoCon+DoRA style LoRA. Inverse alpha/dim ratio (alpha > dim), huge effective batch (6x6=36). NOTE: Original used ADOPTAOScheduleFree optimizer — mapped to AdamW until that package is sourced.",
    "model_type": "SDXL",
    "lora_type": "LoCon", "network_module": "lycoris.kohya",
    "resolution": 1024, "network_dim": 16, "network_alpha": 32,
    "conv_dim": 10, "conv_alpha": 20,
    "unet_lr": 0.0005, "text_encoder_lr": 0.00005,
    "lr_scheduler": "constant_with_warmup", "lr_warmup_steps": 16,
    "optimizer_type": "AdamW",
    "optimizer_args": "betas=(0.8,0.998) weight_decay=2e-07",
    "max_train_epochs": 4, "save_every_n_epochs": 1,
    "train_batch_size": 6, "gradient_accumulation_steps": 6,
    "mixed_precision": "bf16",
    "multires_noise_iterations": 6, "multires_noise_discount": 0.1,
  },
  "justtnp_pose_dora": {
    "name": "JustTNP's Pose DoRA (PonyXL)",
    "description": "PonyXL LoCon+DoRA via LyCORIS. Tiny network (4/2), near-frozen TE, CAME optimizer, 45 images x 2 repeats, keep_tokens: 1.",
    "model_type": "SDXL",
    "lora_type": "LoCon", "network_module": "lycoris.kohya",
    "resolution": 1024, "network_dim": 4, "network_alpha": 2,
    "conv_dim": 4, "conv_alpha": 2,
    "unet_lr": 0.00005, "text_encoder_lr": 0.000001,
    "lr_scheduler": "cosine", "optimizer_type": "CAME",
    "optimizer_args": "weight_decay=0.04",
    "max_train_epochs": 6, "save_every_n_epochs": 1,
    "train_batch_size": 2, "mixed_precision": "bf16",
    "noise_offset": 0.0357, "multires_noise_iterations": 6, "multires_noise_discount": 0.3,
    "min_snr_gamma": 8, "min_snr_gamma_enabled": True,
    "shuffle_caption": True, "keep_tokens": 1, "max_token_length": 225,
  },
  "ai_character_flux_dora": {
    "name": "AI Character Style (Flux DoRA)",
    "description": "Flux Dev DoRA via LyCORIS — tiny 18-image dataset, 100 epochs, polynomial scheduler, aggressive pyramid noise.",
    "model_type": "FLUX",
    "lora_type": "DoRA", "network_module": "lycoris.kohya",
    "resolution": 1024, "network_dim": 12, "network_alpha": 12,
    "unet_lr": 0.0003, "text_encoder_lr": 0.0003,
    "lr_scheduler": "polynomial", "optimizer_type": "AdamW",
    "optimizer_args": "weight_decay=0.1",
    "max_train_epochs": 100, "save_every_n_epochs": 10,
    "train_batch_size": 1, "mixed_precision": "bf16",
    "multires_noise_iterations": 10, "multires_noise_discount": 0.1,
    "min_snr_gamma": 5, "min_snr_gamma_enabled": True,
  },
  "crunchy_character": {
    "name": "Crunchy Character",
    "description": "Base SDXL character LoRA (2024). Adafactor with fixed-LR mode (scale_parameter=False), frozen TE, 5 epochs, batch 2.",
    "model_type": "SDXL",
    "resolution": 1024, "network_dim": 32, "network_alpha": 16,
    "unet_lr": 0.0005, "text_encoder_lr": 0,
    "lr_scheduler": "cosine_with_restarts",
    "optimizer_type": "AdaFactor",
    "optimizer_args": "scale_parameter=False relative_step=False warmup_init=False",
    "max_train_epochs": 5, "save_every_n_epochs": 1,
    "train_batch_size": 2, "mixed_precision": "bf16",
    "noise_offset": 0.1, "multires_noise_iterations": 6, "multires_noise_discount": 0.3,
    "min_snr_gamma": 5, "min_snr_gamma_enabled": True,
  },
  "citrons_pdxl": {
    "name": "Citron's PDXL",
    "description": "Pony Diffusion XL style LoRA. Balanced 1:1 dim/alpha, equal TE/UNet LR, low noise offset, warmup steps.",
    "model_type": "SDXL",
    "resolution": 1024, "network_dim": 32, "network_alpha": 32,
    "unet_lr": 0.0001, "text_encoder_lr": 0.0001,
    "lr_scheduler": "cosine_with_restarts", "lr_warmup_steps": 78,
    "optimizer_type": "AdamW8bit",
    "optimizer_args": "weight_decay=0.1 betas=(0.9,0.99)",
    "max_train_epochs": 10, "save_every_n_epochs": 1,
    "train_batch_size": 1, "mixed_precision": "bf16",
    "noise_offset": 0.03, "multires_noise_iterations": 0,
  },
  "citrons_illustrious": {
    "name": "Citron's Illustrious",
    "description": "Illustrious style LoRA with Adafactor, active TE at 5e-5, and caption shuffling. 305 images x 4 repeats.",
    "model_type": "SDXL",
    "resolution": 1024, "network_dim": 32, "network_alpha": 16,
    "unet_lr": 0.0005, "text_encoder_lr": 0.00005,
    "lr_scheduler": "cosine_with_restarts", "optimizer_type": "AdaFactor",
    "max_train_epochs": 10, "save_every_n_epochs": 1,
    "train_batch_size": 1, "mixed_precision": "bf16",
    "noise_offset": 0.1, "multires_noise_iterations": 6, "multires_noise_discount": 0.3,
    "max_token_length": 225, "shuffle_caption": True,
  },
  "citrons_anima": {
    "name": "Citron's Anima",
    "description": "Anima model style LoRA by Citron. Uses lora_anima network, Qwen VAE, unified LR with warmup, no multinoise.",
    "model_type": "Anima",
    "network_module": "networks.lora_anima",
    "resolution": 1024, "network_dim": 24, "network_alpha": 24,
    "unet_lr": 0.0001, "text_encoder_lr": 0,
    "lr_scheduler": "cosine_with_restarts", "lr_warmup_steps": 100,
    "optimizer_type": "AdamW8bit",
    "optimizer_args": "weight_decay=0.1 betas=(0.9,0.99)",
    "max_train_epochs": 10, "save_every_n_epochs": 1,
    "train_batch_size": 1, "fp8_base": False, "mixed_precision": "bf16",
    "noise_offset": 0.03, "multires_noise_iterations": 0,
    "timestep_sampling": "sigmoid", "sigmoid_scale": 1, "discrete_flow_shift": 1,
  },
  "illustrious_style_baking": {
    "name": "Style Baking",
    "description": "Illustrious style LoRA with frozen text encoder. Run full 20 epochs and pick the best checkpoint.",
    "model_type": "SDXL",
    "resolution": 1024, "network_dim": 32, "network_alpha": 16,
    "unet_lr": 0.0005, "text_encoder_lr": 0,
    "lr_scheduler": "cosine_with_restarts", "optimizer_type": "AdamW8bit",
    "max_train_epochs": 20, "save_every_n_epochs": 1,
    "train_batch_size": 1, "mixed_precision": "bf16",
    "noise_offset": 0.1, "multires_noise_iterations": 6, "multires_noise_discount": 0.3,
    "min_snr_gamma": 5, "min_snr_gamma_enabled": True,
  },
  "chroma_style_experimental": {
    "name": "Chroma Style (Experimental)",
    "description": "Chroma LoRA style training — very low dim/alpha ratio, fp8 base, frozen text encoder. Uses lora_flux network.",
    "model_type": "Chroma",
    "network_module": "networks.lora_flux",
    "resolution": 1024, "network_dim": 2, "network_alpha": 16,
    "unet_lr": 0.0005, "text_encoder_lr": 0,
    "lr_scheduler": "cosine_with_restarts", "optimizer_type": "AdamW8bit",
    "optimizer_args": "weight_decay=0.01 eps=1e-08",
    "max_train_epochs": 20, "save_every_n_epochs": 1,
    "train_batch_size": 2, "fp8_base": True, "mixed_precision": "bf16",
    "noise_offset": 0.1, "multires_noise_iterations": 6, "multires_noise_discount": 0.3,
    "min_snr_gamma": 5, "min_snr_gamma_enabled": True,
    "timestep_sampling": "sigmoid", "sigmoid_scale": 1, "discrete_flow_shift": 3,
    "guidance_scale": 0, "apply_t5_attn_mask": True,
  },
  "illustrious_experimental": {
    "name": "Experimental Training",
    "description": "Illustrious style with unfrozen text encoder and weight decay. More flexible, proceed with curiosity.",
    "model_type": "SDXL",
    "resolution": 1024, "network_dim": 32, "network_alpha": 16,
    "unet_lr": 0.0005, "text_encoder_lr": 0.00001,
    "lr_scheduler": "cosine_with_restarts", "optimizer_type": "AdamW8bit",
    "optimizer_args": "weight_decay=0.1",
    "max_train_epochs": 20, "save_every_n_epochs": 1,
    "train_batch_size": 1, "mixed_precision": "bf16",
    "noise_offset": 0.1, "multires_noise_iterations": 6, "multires_noise_discount": 0.3,
    "min_snr_gamma": 5, "min_snr_gamma_enabled": True,
  },
}

written = 0
skipped = 0
for key, preset in presets.items():
    filepath = os.path.join(PRESETS_DIR, f"{key}.json")
    if os.path.exists(filepath):
        skipped += 1
        continue
    data = {"is_builtin": True, **preset}
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    written += 1

print(f"Written: {written}  Skipped (already exist): {skipped}")
